[
    ./Alacritty/alacritty.nix
    ./Picom/picom.nix
    ./Fish/fish.nix
    ./Ranger/ranger.nix
    ./Dunst/dunst.nix
    ./Editors/Emacs/emacs.nix
    ./Editors/Sublime/sublime.nix
    ./catppuccin.nix
]
